# Optimal hyperparams tested on ASUS A17 with AMD Ryzen 7 6800H and RTX 3050 Laptop GPU
import os

cartpole = {
    "ppo_params": {
        "LR": 3e-4,
        "NUM_AGENTS": 1024,
        "NUM_STEPS": 100,
        "TOTAL_TIMESTEPS": 100_000_000,
        "EPOCHS": 4,
        "NUM_MINIBATCHES": 10,
        "GAMMA": 0.99,
        "GAE_LAMBDA": 0.95,
        "CLIP_EPS": 0.2,
        "CLIP_VALUE": 1.0,
        "ENT_COEF": 0.01,
        "VF_COEF": 0.5,
        "MAX_GRAD_NORM": 1.0,
        "ANNEAL_LR": False,
        "DEBUG": False,
    },
    "env_params": {
        "num_agents": 1024,
        "m_c": 1.0,
        "m_p": 0.1,
        "half_length": 0.5,
        "g": 9.8,
        "force_mag": 5.0,
        "dt": 0.05,
        "x_threshold": 3.0,
        "num_steps": 150,
    },
}

copter2d = {
    "ppo_params": {
        "LR": 3e-4,
        "NUM_AGENTS": 1024,
        "NUM_STEPS": 100,
        "TOTAL_TIMESTEPS": 100_000_000,
        "EPOCHS": 4,
        "NUM_MINIBATCHES": 10,
        "GAMMA": 0.99,
        "GAE_LAMBDA": 0.95,
        "CLIP_EPS": 0.2,
        "CLIP_VALUE": 1.0,
        "ENT_COEF": 0.01,
        "VF_COEF": 0.5,
        "MAX_GRAD_NORM": 1.0,
        "ANNEAL_LR": False,
        "DEBUG": True,
    },
    "env_params": {
        "num_agents": 1024,
        "mass": 1.0,
        "inertia": 1.0,
        "arm_length": 0.5,
        "g": 9.8,
        "thurst_mag": 20.0,
        "torque_mag": 10.0,
        "dt": 0.05,
        "x_threshold": 3.0,
        "num_steps": 100,
    },
}

crazyflie = {
    "ppo_params": {
        "LR": 3e-4,
        "NUM_AGENTS": 128,
        "NUM_STEPS": 300,
        "TOTAL_TIMESTEPS": 20_000_000,
        "EPOCHS": 16,
        "NUM_MINIBATCHES": 8,
        "GAMMA": 0.99,
        "GAE_LAMBDA": 0.95,
        "CLIP_EPS": 0.2,
        "CLIP_VALUE": 1.0,
        "ENT_COEF": 0.01,
        "VF_COEF": 0.5,
        "MAX_GRAD_NORM": 1.0,
        "ANNEAL_LR": False,
        "DEBUG": True,
    },
    "env_params": {
        "num_agents": 128,
        "num_steps": 300,
        "phy_freq": 200,
        "ctrl_freq": 100,
    },
}

maze = {
    "ppo_params": {
        "LR": 3e-4,
        "NUM_AGENTS": 256,
        "NUM_STEPS": 50,
        "TOTAL_TIMESTEPS": 1_000_000,
        "EPOCHS": 8,
        "NUM_MINIBATCHES": 8,
        "GAMMA": 0.99,
        "GAE_LAMBDA": 0.95,
        "CLIP_EPS": 0.2,
        "CLIP_VALUE": 1.0,
        "ENT_COEF": 0.01,
        "VF_COEF": 0.5,
        "MAX_GRAD_NORM": 1.0,
        "ANNEAL_LR": False,
        "DEBUG": True,
    },
    "env_params": {
        "num_agents": 256,
        "num_particles": 8,
        "maze_path": os.path.join(os.path.dirname(__file__), './zoo/assets/maze16.png'),
        "goal_point": (0, 0),
        "num_steps": 50,
        "dt": 0.001,
    },
}